Exercise-3 Completed

diff --git a/.github/workflows/exer-3.4.yaml b/.github/workflows/exer-3.4.yaml
--- a/.github/workflows/exer-3.4.yaml
+++ b/.github/workflows/exer-3.4.yaml
@@ -15,9 +15,9 @@ jobs:
               with:
                   python-version: "3.11"
             - name: Completed
-              run: |
+              run: 
                 echo "Setup done"
-                exit 1 # Deliberately fail the setup job to test the pipeline behavior
+                # exit 1 - Deliberately fail the setup job to test the pipeline behavior
 
     verify:
         runs-on: ubuntu-latest
